#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — one stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# Pier release signing. The release workflow (.github/workflows/release.yml)
# signs the app with a Developer ID Application certificate and notarizes it
# with an Apple ID. This wizard collects the five repository secrets it reads:
#   CSC_LINK, CSC_KEY_PASSWORD, APPLE_ID, APPLE_APP_SPECIFIC_PASSWORD, APPLE_TEAM_ID
# Nothing is written to disk here; the values go straight to GitHub.
#
# Run from anywhere: scripts/setup-signing.sh

cd "$(dirname "$0")/.."
ENV_FILE="/dev/null"   # secrets are never persisted locally

TOTAL_STAGES=3

banner "Pier release signing"

# ── Stage 1: the certificate ───────────────────────────────────────────────
stage "Developer ID certificate"
say "CI needs your Developer ID Application certificate as a password-protected .p12."
say "Keychain Access exports it; the export prompts for a password of your choosing."
IDENTITY=$(security find-identity -v -p codesigning 2>/dev/null | grep -o '"Developer ID Application: [^"]*"' | head -1 | tr -d '"' || true)
if [[ -n "$IDENTITY" ]]; then
  note "found in your keychain: $IDENTITY"
else
  warn "no Developer ID Application identity found in the login keychain"
  say "Create one at https://developer.apple.com/account/resources/certificates/add (type: Developer ID Application),"
  say "download it, double-click to add it to the login keychain, then re-run this wizard."
  exit 1
fi
P12_DEFAULT="$HOME/Desktop/pier-developer-id.p12"
say ""
step "Keychain Access is opening. In the sidebar pick 'login', then the 'My Certificates' tab."
step "Right-click '$IDENTITY' and choose 'Export…'."
step "File format: Personal Information Exchange (.p12). Save it as:"
say "    $P12_DEFAULT"
step "Set an export password when asked (you will paste it below), then allow the keychain to export the key."
open -a "Keychain Access" >/dev/null 2>&1 || warn "could not open Keychain Access; open it from Applications/Utilities"
pause "Press Enter once the .p12 is saved."
ask P12_PATH "Path to the .p12 [$P12_DEFAULT]:"
P12_PATH="${P12_PATH:-$P12_DEFAULT}"
P12_PATH="${P12_PATH/#\~/$HOME}"
until [[ -f "$P12_PATH" ]]; do
  warn "no file at $P12_PATH"
  ask P12_PATH "Path to the .p12:"
  P12_PATH="${P12_PATH/#\~/$HOME}"
done
ask_secret CSC_KEY_PASSWORD "Export password you set:"
if openssl pkcs12 -in "$P12_PATH" -passin "pass:$CSC_KEY_PASSWORD" -nokeys -noout >/dev/null 2>&1 \
   || openssl pkcs12 -legacy -in "$P12_PATH" -passin "pass:$CSC_KEY_PASSWORD" -nokeys -noout >/dev/null 2>&1; then
  note "the .p12 opens with that password"
else
  warn "could not open the .p12 with that password"
  confirm "Continue anyway?" || exit 1
fi
CSC_LINK=$(base64 < "$P12_PATH" | tr -d '\n')
set_secret CSC_LINK "$CSC_LINK"
set_secret CSC_KEY_PASSWORD "$CSC_KEY_PASSWORD"

# ── Stage 2: notarization credentials ──────────────────────────────────────
stage "Apple ID for notarization"
say "Notarization signs in with your Apple ID and an app-specific password (not your account password)."
TEAM_ID=$(printf '%s' "$IDENTITY" | grep -o '([A-Z0-9]*)$' | tr -d '()' || true)
if [[ -n "$TEAM_ID" ]]; then note "team id from the certificate: $TEAM_ID"; fi
open_url "https://account.apple.com/account/manage"
step "Sign in, then under 'Sign-In and Security' open 'App-Specific Passwords'."
step "Click the plus button, name it 'Pier notarization', and copy the generated password."
ask APPLE_ID "Apple ID email (the developer account):"
until [[ "$APPLE_ID" == *@* ]]; do ask APPLE_ID "Apple ID email:"; done
ask_secret APPLE_APP_SPECIFIC_PASSWORD "App-specific password:"
if [[ -z "$TEAM_ID" ]]; then
  say "The team id is shown at https://developer.apple.com/account under Membership details."
  ask TEAM_ID "Team id:"
fi
set_secret APPLE_ID "$APPLE_ID"
set_secret APPLE_APP_SPECIFIC_PASSWORD "$APPLE_APP_SPECIFIC_PASSWORD"
set_secret APPLE_TEAM_ID "$TEAM_ID"

# ── Stage 3: verify and clean up ───────────────────────────────────────────
stage "Verify"
say "Secrets now on the repository:"
gh secret list 2>/dev/null | sed 's/^/    /' || warn "gh could not list secrets"
say ""
say "The exported .p12 holds your private key. It is already in GitHub and in your keychain."
if confirm "Delete $P12_PATH now?"; then
  rm -f "$P12_PATH" && note "deleted"
fi
say ""
say "Next: push a v* tag. The release workflow will sign, notarize, and publish the DMG."

finish
